### ISSUE TITLE
publishing to npm

### ISSUE THREAD

**Issue by coolaj86** [michielbdejong/node-letsencrypt#3]
If you give me your npm name I'll add you to the owner list so you can publish your updates.

https://github.com/letsencrypt/node-acme/issues/16

**Comment by michielbdejong** [comment]
Oh, thanks! On npm, I'm https://www.npmjs.com/~michielbdejong.

I'm confused though, because publishing my changes only to npm would mean your npm package gets ahead of your github master, which would be confusing, right?

Also, you as an organization would then be npm-publishing unreviewed code under your name. If you want to publish my changes then the easiest way would be to merge my [pull requests](https://github.com/letsencrypt/node-acme/pulls) into master, then update package.json and tag a git version, then push that to npm.

That's why I started this bugfixing fork, and published it on npm (in my personal name, so it's clear that it was not reviewed by you) as 'node-letsencrypt'. And if people want to play it safe, they can still use your official 'node-acme' npm package.

**Comment by coolaj86** [comment]
Hehehe. I'm not a project member, I just grabbed the npm module name because I trust myself to do the right thing with it than I trust someone else.


That said, as mentioned on the issue I've already established that I will relinquish to the rightful owner if they ever want to claim it.


—

**Comment by coolaj86** [comment]
P.S. I added you as an owner.

**Comment by michielbdejong** [comment]
ok so then let's agree that the node-acme package tracks https://github.com/letsencrypt/node-acme/blob/master/package.json and either you or I or someone else can npm publish it whenever the version number updates in the master branch there. I will keep publishing this bugfixing fork on npm as node-letsencrypt whenever I update it, but hopefully we can merge it back in at some point.

Thanks for adding me!
